# Generated by Django 3.0.8 on 2020-09-13 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
                ('slug', models.SlugField()),
                ('subcategories', models.ManyToManyField(blank=True, related_name='_category_subcategories_+', to='avto.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_volue', models.IntegerField(choices=[(800, 'Eight Hundred'), (900, 'Nine Hundred'), (1000, 'One Thousand'), (1100, 'Eleven Hundred'), (1200, 'Twelwe Hundred'), (1300, 'Thirting Hundred')], default=1300, verbose_name='Объем двигателя')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('categories', models.ManyToManyField(blank=True, to='avto.Category')),
            ],
        ),
        migrations.CreateModel(
            name='ModelImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='models/%Y/%m/%d/')),
                ('image_base64', models.TextField(blank=True, default=None, null=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_model', to='avto.Model')),
            ],
        ),
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('year_begin', models.PositiveIntegerField()),
                ('year_end', models.PositiveIntegerField()),
                ('models', models.ManyToManyField(to='avto.Model')),
            ],
        ),
    ]
