# Generated by Django 3.0.8 on 2020-09-17 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('title',), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AddField(
            model_name='characteristic',
            name='body_type',
            field=models.CharField(choices=[('Cargo Van', 'Грузовой фургон'), ('Convertible', 'Кабриолет'), ('Coupe', 'Купе'), ('Hatchback', 'Хетчбэк'), ('Limousine', 'Лимузин'), ('Minivan', 'Минивэн'), ('Passenger Van', 'Микроавтобус'), ('Pickup', 'Пикап'), ('Sedan', 'Седан'), ('SUV', 'Внедорожник'), ('Wagon', 'Универсал')], default='Sedan', max_length=15, verbose_name='Тип кузова'),
        ),
        migrations.AddField(
            model_name='characteristic',
            name='door',
            field=models.CharField(choices=[(2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six')], default=4, max_length=1, verbose_name='Количество дверей'),
        ),
        migrations.AddField(
            model_name='characteristic',
            name='drivetrain',
            field=models.CharField(choices=[('AWD', 'Полный привод'), ('FWD', 'Передний привод'), ('RWD', 'Задний привод')], default='FWD', max_length=17, verbose_name='Привод'),
        ),
        migrations.AddField(
            model_name='characteristic',
            name='flue',
            field=models.CharField(choices=[('Natural Gas', 'Газ'), ('Gasoline', 'Бензин'), ('Gasoline Hybrid', 'Гибрид'), ('Diesel', 'Дизель'), ('Electric', 'Электро')], default='Gasoline', max_length=15, verbose_name='Вид топлива'),
        ),
        migrations.AddField(
            model_name='characteristic',
            name='gearbox',
            field=models.CharField(choices=[('Manual', ' Механическая'), ('Automatic', 'Автоматическая')], default='Automatic', max_length=15, verbose_name='Коробка передач'),
        ),
        migrations.AddField(
            model_name='characteristic',
            name='mileage',
            field=models.FloatField(blank=True, null=True, verbose_name='Пробег'),
        ),
        migrations.AddField(
            model_name='characteristic',
            name='models',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Characteristic', to='avto.Model'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='characteristic',
            name='seat',
            field=models.CharField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six'), (7, 'Seven'), (8, 'Eight'), (9, 'Nine'), (10, 'Ten'), (11, 'Eleven'), (12, 'Twelwe')], default=5, max_length=2, verbose_name='Количество мест'),
        ),
        migrations.AddField(
            model_name='model',
            name='brends',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='models', to='avto.Brend'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brend',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='engine_volue',
            field=models.IntegerField(choices=[(800, 'Eight Hundred'), (900, 'Nine Hundred'), (1000, 'One Thousand'), (1100, 'Eleven Hundred'), (1200, 'Twelwe Hundred'), (1300, 'Thirting Hundred'), (1400, 'Fourteen Hundred'), (1500, 'Fifteen Hundred'), (1600, 'Sixteen Hundred'), (1700, 'Seventeen Hundred'), (1800, 'Eighteen Hundred'), (1900, 'Nineteen Hundred'), (2000, 'Twenty Hundred'), (2100, 'Twenty One Hundred'), (2200, 'Twenty Two Hundred'), (2300, 'Twenty Three Hundred'), (2400, 'Twenty Four Hundred'), (2500, 'Twenty Five Hundred'), (2600, 'Twenty Six Hundred'), (2700, 'Twenty Seven Hundred'), (2800, 'Twenty Eight Hundred'), (2900, 'Twenty Nine Hundred'), (3000, 'Thirty Hundred'), (3100, 'Thirty One Hundred'), (3200, 'Thirty Two Hundred'), (3500, 'Thirty Five Hundred'), (3600, 'Thirty Six Hundred'), (4000, 'Fourty Hundred'), (4500, 'Fourty Five Hundred'), (5000, 'Fifty Hundred'), (5500, 'Fifty Five Hundred'), (6000, 'Sixty Hundred'), (7000, 'Seventy Hundred'), (8000, 'Eighty Hundred')], default=1300, verbose_name='Объем двигателя'),
        ),
    ]
