# Generated by Django 3.0.8 on 2020-09-17 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avto', '0006_auto_20200917_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='consumption',
        ),
        migrations.AddField(
            model_name='equipment',
            name='consumption_city',
            field=models.FloatField(blank=True, null=True, verbose_name='Расход город'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='consumption_road',
            field=models.FloatField(blank=True, null=True, verbose_name='Расход трасса'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='door',
            field=models.IntegerField(choices=[(2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six')], default=4, verbose_name='Количество дверей'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='generations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Characteristic', to='avto.Generation', verbose_name='Поколение'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='seat',
            field=models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six'), (7, 'Seven'), (8, 'Eight'), (9, 'Nine'), (10, 'Ten'), (11, 'Eleven'), (12, 'Twelwe')], default=5, verbose_name='Количество мест'),
        ),
    ]
