# Generated by Django 3.0.8 on 2020-09-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avto', '0007_auto_20200917_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='brend',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
