# Generated by Django 3.0.8 on 2020-09-18 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avto', '0008_auto_20200918_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelimage',
            name='image',
            field=models.ImageField(upload_to='generations/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='modelimage',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_model', to='avto.Generation'),
        ),
    ]
