# Generated by Django 3.0.8 on 2020-09-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avto', '0009_auto_20200918_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelimage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
